# Generated by Django 4.0.2 on 2022-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_myapp_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myapp',
            options={'ordering': ['id'], 'verbose_name_plural': 'my apps'},
        ),
        migrations.AddField(
            model_name='myapp',
            name='url',
            field=models.CharField(default='/supplychain', max_length=30),
            preserve_default=False,
        ),
    ]
